"""base

Revision ID: 50ef90a799b1
Revises: 
Create Date: 2025-04-17 23:32:10.279083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ef90a799b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('effect',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('value_type', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('attribute', sa.String(length=50), nullable=True),
    sa.Column('scaling_stat', sa.String(length=50), nullable=True),
    sa.Column('trigger_condition', sa.String(length=50), nullable=True),
    sa.Column('stackable', sa.Boolean(), nullable=True),
    sa.Column('set_bonus_group', sa.String(length=100), nullable=True),
    sa.Column('icon_path', sa.String(length=256), nullable=True),
    sa.Column('related_items', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('rarity', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('equipment_slot', sa.String(length=50), nullable=True),
    sa.Column('weapon_slot_type', sa.String(length=50), nullable=True),
    sa.Column('item_stats', sa.JSON(), nullable=True),
    sa.Column('attributes_bonus', sa.JSON(), nullable=True),
    sa.Column('effects', sa.JSON(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('is_quest_item', sa.Boolean(), nullable=True),
    sa.Column('is_consumable', sa.Boolean(), nullable=True),
    sa.Column('is_material', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('image_path', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('effect')
    # ### end Alembic commands ###
