import type { PresetScope } from './types';

export const effectsPresets: PresetScope = {
  schema: 'effects',
  presets: [
    {
      id: 'effect-damage-flat',
      label: 'Effect: Flat Damage',
      description: 'Baseline direct damage payload for abilities or items.',
      category: 'Mechanics',
      intent: 'damage',
      difficulty: 'starter',
      tags: ['damage', 'combat'],
      defaultMode: 'fill_empty',
      data: {
        type: 'Damage',
        target: 'Enemy',
        value_type: 'Flat',
        value: 20,
        calculation_basis: 'Fixed Value',
        scaling_multiplier: 0,
        duration: 0,
        trigger_condition: 'None',
        stackable: false,
        description: 'Deals direct damage to the target.',
        tags: ['damage', 'direct'],
      },
    },
    {
      id: 'effect-status-control',
      label: 'Effect: Status Control',
      description: 'Status application scaffold with chance and duration.',
      category: 'Mechanics',
      intent: 'control',
      difficulty: 'intermediate',
      tags: ['status', 'control'],
      defaultMode: 'fill_empty',
      data: {
        type: 'Status',
        target: 'Enemy',
        value_type: 'None',
        calculation_basis: 'Fixed Value',
        scaling_multiplier: 0,
        duration: 3,
        apply_chance: 75,
        trigger_condition: 'On Cast',
        stackable: false,
        description: 'Applies a control status for a limited duration.',
        tags: ['status', 'control'],
      },
    },
    {
      id: 'effect-lifesteal',
      label: 'Effect: Lifesteal',
      description: 'Reusable heal based on damage dealt.',
      category: 'Mechanics',
      intent: 'heal',
      difficulty: 'intermediate',
      tags: ['heal', 'lifesteal', 'weapon'],
      defaultMode: 'fill_empty',
      data: {
        type: 'Heal',
        target: 'Self',
        value_type: 'Percentage',
        value: 10,
        calculation_basis: 'Damage Dealt',
        scaling_multiplier: 0,
        duration: 0,
        apply_chance: 100,
        trigger_condition: 'On Hit',
        stackable: false,
        description: 'Heals the source for a percentage of damage dealt.',
        tags: ['heal', 'lifesteal'],
      },
    },
    {
      id: 'effect-burning-dot',
      label: 'Effect: Burning DoT',
      description: 'Status application with per-tick fire damage tuning.',
      category: 'Mechanics',
      intent: 'damage-over-time',
      difficulty: 'intermediate',
      tags: ['status', 'burn', 'dot', 'fire'],
      defaultMode: 'fill_empty',
      data: {
        type: 'Status',
        target: 'Enemy',
        value_type: 'Flat',
        value: 8,
        calculation_basis: 'Source Stat',
        scaling_multiplier: 0.2,
        damage_type: 'Fire',
        tick_interval: 1,
        duration: 5,
        apply_chance: 50,
        trigger_condition: 'On Cast',
        stackable: false,
        description: 'Applies Burn and stores fire damage per tick on the active status instance.',
        tags: ['status', 'burn', 'dot', 'fire'],
      },
    },
  ],
};
