import type { PresetScope } from './types';

export const fantasyAbilityPresets: PresetScope = {
  schema: 'abilities',
  presets: [
    {
      id: 'fantasy-ability-arcane-bolt',
      label: 'Fantasy: Arcane Bolt',
      description: 'Classic single-target spell attack for apprentices, cultists, or battle mages.',
      category: 'Fantasy RPG',
      tags: ['spell', 'arcane', 'damage'],
      defaultMode: 'fill_empty',
      scope: 'entry',
      outputKind: 'patch',
      riskLevel: 'low',
      data: {
        name: 'Arcane Bolt',
        slug: 'arcane-bolt',
        type: 'Active',
        targeting: 'Single',
        trigger_condition: 'On Use',
        damage_type_source: 'Fixed',
        damage_type: 'Light',
        resource_cost: 8,
        cooldown: 1,
        description: 'A focused lance of raw magic strikes a single foe.',
        tags: ['spell', 'arcane', 'single_target'],
      },
    },
    {
      id: 'fantasy-ability-shield-wall',
      label: 'Fantasy: Shield Wall',
      description: 'Defensive martial ability for guards, knights, and shield-bearing companions.',
      category: 'Fantasy RPG',
      tags: ['martial', 'defense', 'tank'],
      defaultMode: 'fill_empty',
      scope: 'entry',
      outputKind: 'patch',
      riskLevel: 'low',
      data: {
        name: 'Shield Wall',
        slug: 'shield-wall',
        type: 'Active',
        targeting: 'Self',
        trigger_condition: 'On Use',
        damage_type_source: 'None',
        resource_cost: 6,
        cooldown: 3,
        description: 'Brace behind a shield, reducing incoming pressure and holding the line.',
        tags: ['martial', 'defense', 'frontline'],
      },
    },
    {
      id: 'fantasy-ability-shadow-step',
      label: 'Fantasy: Shadow Step',
      description: 'Mobility and ambush setup for rogues, assassins, and shadow cultists.',
      category: 'Fantasy RPG',
      tags: ['rogue', 'shadow', 'mobility'],
      defaultMode: 'fill_empty',
      scope: 'entry',
      outputKind: 'patch',
      riskLevel: 'low',
      data: {
        name: 'Shadow Step',
        slug: 'shadow-step',
        type: 'Active',
        targeting: 'Self',
        trigger_condition: 'On Use',
        damage_type_source: 'None',
        resource_cost: 12,
        cooldown: 4,
        description: 'Slip through nearby darkness to reposition for an ambush.',
        tags: ['rogue', 'shadow', 'mobility'],
      },
    },
  ],
};

export const fantasyItemPresets: PresetScope = {
  schema: 'items',
  presets: [
    {
      id: 'fantasy-item-silvered-longsword',
      label: 'Fantasy: Silvered Longsword',
      description: 'Reliable monster-hunting weapon suited for crypts, curses, and undead threats.',
      category: 'Fantasy RPG',
      tags: ['weapon', 'monster_hunter', 'silver'],
      defaultMode: 'fill_empty',
      scope: 'entry',
      outputKind: 'patch',
      riskLevel: 'low',
      data: {
        name: 'Silvered Longsword',
        slug: 'silvered-longsword',
        type: 'Weapon',
        rarity: 'Uncommon',
        equipment_slot: 'main_hand',
        weapon_type: 'Longsword',
        damage_type: 'Slashing',
        weapon_range_type: 'melee',
        weapon_range: 1,
        base_price: 250,
        description: 'A balanced longsword edged with alchemical silver for hunting cursed creatures.',
        tags: ['weapon', 'silver', 'undead_hunter'],
      },
    },
    {
      id: 'fantasy-item-delve-kit',
      label: 'Fantasy: Delver Kit',
      description: 'Practical adventuring kit for underground expeditions.',
      category: 'Fantasy RPG',
      tags: ['tool', 'dungeon', 'exploration'],
      defaultMode: 'fill_empty',
      scope: 'entry',
      outputKind: 'patch',
      riskLevel: 'low',
      data: {
        name: 'Delver Kit',
        slug: 'delver-kit',
        type: 'Tool',
        rarity: 'Common',
        base_price: 75,
        description: 'Chalk, twine, pitons, waxed cloth, and a compact lantern for careful dungeon travel.',
        tags: ['tool', 'dungeon', 'exploration'],
      },
    },
    {
      id: 'fantasy-item-potion-moonlit-vigor',
      label: 'Fantasy: Potion of Moonlit Vigor',
      description: 'Consumable recovery item with a mystical wilderness tone.',
      category: 'Fantasy RPG',
      tags: ['consumable', 'potion', 'healing'],
      defaultMode: 'fill_empty',
      scope: 'entry',
      outputKind: 'patch',
      riskLevel: 'low',
      data: {
        name: 'Potion of Moonlit Vigor',
        slug: 'potion-of-moonlit-vigor',
        type: 'Consumable',
        rarity: 'Uncommon',
        base_price: 90,
        description: 'A blue-silver tonic brewed by grove alchemists to restore strength after battle.',
        tags: ['consumable', 'potion', 'healing', 'moonlit'],
      },
    },
  ],
};

export const fantasyQuestPresets: PresetScope = {
  schema: 'quests',
  presets: [
    {
      id: 'fantasy-quest-dungeon-contract',
      label: 'Fantasy: Dungeon Contract',
      description: 'A compact dungeon-delving quest scaffold with objectives and rewards.',
      category: 'Fantasy RPG',
      tags: ['quest', 'dungeon', 'contract'],
      defaultMode: 'fill_empty',
      scope: 'entry',
      outputKind: 'patch',
      riskLevel: 'low',
      data: {
        title: 'Contract: The Sealed Cellar',
        slug: 'contract-the-sealed-cellar',
        description: 'A patron hires the party to investigate an old sealed cellar beneath a troubled settlement.',
        objectives: [
          { objective_id: 'obj_1', description: 'Enter the sealed cellar.' },
          { objective_id: 'obj_2', description: 'Find the source of the disturbances.' },
          { objective_id: 'obj_3', description: 'Return with proof of what happened below.' },
        ],
        xp_reward: 150,
        currency_rewards: [{ currency_id: '', amount: 75 }],
        item_rewards: [{ item_id: '', quantity: 1 }],
        tags: ['quest', 'dungeon', 'contract'],
      },
    },
  ],
};

export const fantasyEncounterPresets: PresetScope = {
  schema: 'encounters',
  presets: [
    {
      id: 'fantasy-encounter-ambush',
      label: 'Fantasy: Cave Raider Ambush',
      description: 'Simple hostile encounter scaffold for roads, caves, and ruins.',
      category: 'Fantasy RPG',
      tags: ['encounter', 'ambush', 'hostile'],
      defaultMode: 'fill_empty',
      scope: 'entry',
      outputKind: 'patch',
      riskLevel: 'low',
      data: {
        name: 'Cave Raider Ambush',
        slug: 'cave-raider-ambush',
        encounter_type: 'Combat',
        description: 'Small raiders strike from cover, testing player positioning and target priority.',
        participants: [{ character_id: '', contexts: ['Combat'], combat_side: 'Hostile' }],
        rewards: { xp: 100, items: [], currencies: [{ currency_id: '', amount: 20 }], reputation: [], flags_set: [] },
        tags: ['combat', 'ambush', 'low_level'],
      },
    },
    {
      id: 'fantasy-encounter-ancient-guardian',
      label: 'Fantasy: Ancient Guardian',
      description: 'Elite dungeon guardian encounter with stronger rewards.',
      category: 'Fantasy RPG',
      tags: ['encounter', 'guardian', 'elite'],
      defaultMode: 'fill_empty',
      scope: 'entry',
      outputKind: 'patch',
      riskLevel: 'medium',
      data: {
        name: 'Ancient Guardian',
        slug: 'ancient-guardian',
        encounter_type: 'Combat',
        description: 'A ward-bound sentinel protects a sealed chamber from intruders.',
        participants: [{ character_id: '', contexts: ['Combat'], combat_side: 'Hostile' }],
        rewards: { xp: 350, items: [{ item_id: '', quantity: 1 }], currencies: [{ currency_id: '', amount: 60 }], reputation: [], flags_set: [] },
        tags: ['combat', 'guardian', 'elite', 'dungeon'],
      },
    },
  ],
};

export const fantasyWorldPresets: PresetScope[] = [
  {
    schema: 'locations',
    presets: [
      {
        id: 'fantasy-location-ruined-keep',
        label: 'Fantasy: Ruined Keep',
        description: 'Explorable ruined stronghold with dungeon hooks.',
        category: 'Fantasy RPG',
        tags: ['location', 'ruins', 'dungeon'],
        defaultMode: 'fill_empty',
        scope: 'entry',
        outputKind: 'patch',
        riskLevel: 'low',
        data: {
          name: 'Ruined Keep of Thornwatch',
          slug: 'ruined-keep-of-thornwatch',
          description: 'A broken hilltop fortress whose lower vaults still hold old wards, hungry things, and sealed doors.',
          tags: ['ruins', 'keep', 'dungeon', 'adventure_site'],
        },
      },
    ],
  },
  {
    schema: 'factions',
    presets: [
      {
        id: 'fantasy-faction-lantern-order',
        label: 'Fantasy: Lantern Order',
        description: 'Monster-hunting order for quests, vendors, and reputation rewards.',
        category: 'Fantasy RPG',
        tags: ['faction', 'order', 'monster_hunters'],
        defaultMode: 'fill_empty',
        scope: 'entry',
        outputKind: 'patch',
        riskLevel: 'low',
        data: {
          name: 'Order of the Last Lantern',
          slug: 'order-of-the-last-lantern',
          description: 'A stern fellowship of wardens, scouts, and oathbound monster hunters.',
          tags: ['order', 'monster_hunters', 'wardens'],
        },
      },
    ],
  },
  {
    schema: 'lore_entries',
    presets: [
      {
        id: 'fantasy-lore-sealed-vault',
        label: 'Fantasy: Sealed Vault Rumor',
        description: 'Lore seed for a dungeon secret, quest clue, or tavern rumor.',
        category: 'Fantasy RPG',
        tags: ['lore', 'rumor', 'dungeon'],
        defaultMode: 'fill_empty',
        scope: 'entry',
        outputKind: 'patch',
        riskLevel: 'low',
        data: {
          title: 'The Sealed Vault Below',
          slug: 'the-sealed-vault-below',
          content: 'Old masons claimed the lower vault was sealed from the inside, not the outside.',
          tags: ['rumor', 'dungeon', 'sealed_vault'],
        },
      },
    ],
  },
];
